//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Plug-in manager for Window\'s applications")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.1.0.0-2201030958")]
[assembly: System.Reflection.AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyProduct("TNT Plug-in Manager")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Tripp\'n Technology, LLC. 2022")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.0.0")]
[assembly: System.Reflection.AssemblyVersion("1.1.0.0")]
[assembly: System.Reflection.AssemblyTitle("TNT Plug-in Manager")]


